# Generated by Django 4.1 on 2022-08-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=500, verbose_name='название города')),
                ('city_url', models.TextField(verbose_name='ссылка на город')),
                ('weather_info', models.TextField(verbose_name='информация по погоде')),
            ],
            options={
                'verbose_name': 'Погода1',
                'verbose_name_plural': 'Погода2',
            },
        ),
    ]
