# Generated by Django 4.1 on 2022-08-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_weathermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathermodel',
            name='weather_info',
            field=models.TextField(blank=True, verbose_name='информация по погоде'),
        ),
    ]
