# Generated by Django 4.1 on 2022-08-15 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_app', '0003_alter_weathermodel_weather_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='морож')),
                ('description', models.TextField(blank=True, default='Описание', verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='IcecreamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='категория морож')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории морож',
            },
        ),
        migrations.CreateModel(
            name='LikeforIcecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icecream_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.icecream')),
                ('user_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentForIcecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True, default='Комментарии', verbose_name='комментарии')),
                ('datetime_field', models.DateTimeField(auto_now_add=True)),
                ('icecream_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.icecream')),
            ],
            options={
                'verbose_name': 'Комментарий к истории',
                'verbose_name_plural': 'комментарии к историям',
            },
        ),
    ]
