# Generated by Django 4.1 on 2022-08-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_icecream_icecreamcategory_likeforicecream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='category_id',
            field=models.ManyToManyField(blank=True, to='django_app.icecreamcategory', verbose_name='Категория мороженого'),
        ),
    ]
